#!/bin/bash

eval $(cat ~/.fehbg) &

# setting keuboard layout /usr/share/X11/xkb/rules/base.lst
setxkbmap us intl &
xbacklight -set 20 &

xset +fp /usr/share/fonts/local &
xset fp rehash &

NetworkManager &
nm-applet &

~/bin/insync-portable/insync-portable start &

# transmission-gtk &
parcellite &
#xfce4-volumed &
#xscreensaver &
xfce4-power-manager &

#Set status bar & start DWM
# dwmstatus &
#xinput set-button-map 9 1 2 3 5 4 & # Keyboard in natural scrolling
1pantalla.sh &
wmname LG3D &
xcompmgr -f -D 2 &
conky &
redshift -c ~/.config/redshift.conf -v &

exec dwm
