#!/bin/bash

# setting keuboard layout /usr/share/X11/xkb/rules/base.lst
setxkbmap us intl &
xbacklight -set 20 &

xset +fp /usr/share/fonts/local &
xset fp rehash &

NetworkManager &
nm-applet &

~/bin/insync-bin start &

parcellite &
xfce4-power-manager &

wmname LG3D &
xcompmgr -f -D 2 &
conky &
redshift -c ~/.config/redshift.conf -v &
~/bin/display_date.py &
/usr/local/bin/1pantalla.sh &
mount ~/nextcloud &
~/.fehbg &
nmcli radio all off &
xinput set-prop 10 274 0 &
xinput set-prop 10 275 1 &
xinput set-prop 10 291 1 &
ntpd -g -q &
thunderbird &
keepassxc &
terminator &

exec dwm
